-- Создание таблиц
CREATE TABLE public.courses (
    id bigint NOT NULL,
    badge character varying(255),
    difficulty character varying(255),
    duration_weeks integer,
    lessons_count integer,
    short_description character varying(2000),
    slug character varying(255) NOT NULL,
    tags character varying(500),
    title character varying(255) NOT NULL
);

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    content text,
    "position" integer,
    title character varying(255) NOT NULL,
    course_id bigint NOT NULL
);

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Первичные ключи
ALTER TABLE ONLY public.courses ADD CONSTRAINT courses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lessons ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.courses ADD CONSTRAINT ukrbsoo34muf0lcryn4q2i0h3vc UNIQUE (slug);

-- Вставка курса
INSERT INTO public.courses (id, badge, difficulty, duration_weeks, lessons_count, short_description, slug, tags, title) VALUES
(1, 'Начинающий', 'Легкая', 8, 5, 'Изучите основы Java с нуля: синтаксис, переменные, условные операторы, циклы и методы.', 'java-beginners', 'Java,Синтаксис,Переменные,Условия,Циклы,Методы', 'Java для начинающих');

-- Вставка уроков
INSERT INTO public.lessons (id, content, "position", title, course_id) VALUES
(1, 'Цель урока: установить JDK и написать первую программу.

1. JDK (Java Development Kit) - это набор инструментов для разработки на Java. Скачайте JDK с официального сайта Oracle.

2. После установки проверьте версию в командной строке:
   java -version
   javac -version

3. Создайте файл HelloWorld.java:
   public class HelloWorld {
       public static void main(String[] args) {
           System.out.println("Привет, мир!");
       }
   }

4. Скомпилируйте и запустите:
   javac HelloWorld.java
   java HelloWorld

5. Разбор программы:
   - public class HelloWorld - объявление класса
   - public static void main - точка входа
   - System.out.println - вывод на экран

Практика: измените текст приветствия и добавьте вывод вашего имени.', 1, 'Установка JDK и первая программа', 1),

(2, 'Цель урока: изучить переменные и базовые типы данных.

1. Переменная - это ячейка памяти для хранения данных. У каждой переменной есть имя, тип и значение.

2. Примитивные типы данных:
   - byte: 1 байт, числа от -128 до 127
   - short: 2 байта, числа от -32768 до 32767  
   - int: 4 байта, числа от -2^31 до 2^31-1
   - long: 8 байт, нужен суффикс L в конце
   - float: 4 байта, нужен суффикс f
   - double: 8 байт
   - char: 2 байта, символ в ''
   - boolean: true или false

3. Примеры:
   int age = 25;
   double price = 99.99;
   char grade = ''A'';
   boolean isStudent = true;
   String name = "Иван"; // String - это класс, не примитив

4. Ввод с клавиатуры:
   import java.util.Scanner;
   Scanner scanner = new Scanner(System.in);
   System.out.print("Введите имя: ");
   String inputName = scanner.nextLine();
   System.out.print("Введите возраст: ");
   int inputAge = scanner.nextInt();

Практика: создайте программу, которая запрашивает имя и возраст, затем выводит приветствие.', 2, 'Переменные и типы данных', 1),

(3, 'Цель урока: научиться использовать условные операторы.

1. Оператор if:
   if (условие) {
       // код если условие истинно
   }

2. Оператор if-else:
   if (условие) {
       // код если условие истинно
   } else {
       // код если условие ложно
   }

3. Оператор if-else if-else:
   if (условие1) {
       // код если условие1 истинно
   } else if (условие2) {
       // код если условие2 истинно
   } else {
       // код если все условия ложны
   }

4. Оператор switch:
   switch(переменная) {
       case значение1:
           // код
           break;
       case значение2:
           // код
           break;
       default:
           // код
   }

5. Примеры:
   int age = 18;
   if (age >= 18) {
       System.out.println("Вы совершеннолетний");
   } else {
       System.out.println("Вы несовершеннолетний");
   }

   int day = 3;
   switch(day) {
       case 1:
           System.out.println("Понедельник");
           break;
       case 2:
           System.out.println("Вторник");
           break;
       case 3:
           System.out.println("Среда");
           break;
       default:
           System.out.println("Неизвестный день");
   }

Практика: напишите программу, которая определяет время суток по часу (0-23).', 3, 'Условные операторы', 1),

(4, 'Цель урока: изучить циклы для повторения действий.

1. Цикл while - выполняется пока условие истинно:
   int i = 1;
   while (i <= 5) {
       System.out.println("i = " + i);
       i++;
   }

2. Цикл do-while - выполняется минимум один раз:
   int j = 1;
   do {
       System.out.println("j = " + j);
       j++;
   } while (j <= 5);

3. Цикл for - для известного количества повторений:
   for (int k = 1; k <= 5; k++) {
       System.out.println("k = " + k);
   }

4. Вложенные циклы:
   for (int i = 1; i <= 3; i++) {
       for (int j = 1; j <= 3; j++) {
           System.out.print(i * j + " ");
       }
       System.out.println();
   }

5. Операторы управления циклом:
   - break - прерывает цикл
   - continue - переходит к следующей итерации

   for (int i = 1; i <= 10; i++) {
       if (i == 5) continue; // пропустить 5
       if (i == 8) break;    // остановиться на 8
       System.out.println(i);
   }

Практика: выведите таблицу умножения от 1 до 10 используя вложенные циклы.', 4, 'Циклы', 1),

(5, 'Цель урока: научиться создавать и использовать методы.

1. Метод - это блок кода, который можно вызвать многократно:
   [модификаторы] тип_возврата имя_метода([параметры]) {
       // тело метода
       return значение;
   }

2. Простой метод без параметров:
   public static void sayHello() {
       System.out.println("Привет!");
   }

3. Метод с параметрами:
   public static void printSum(int a, int b) {
       System.out.println("Сумма: " + (a + b));
   }

4. Метод с возвращаемым значением:
   public static int getSum(int a, int b) {
       return a + b;
   }

5. Перегрузка методов - одинаковое имя, разные параметры:
   public static int multiply(int a, int b) {
       return a * b;
   }
   
   public static double multiply(double a, double b) {
       return a * b;
   }

6. Пример использования:
   public static void main(String[] args) {
       sayHello();
       printSum(5, 3);
       int result = getSum(10, 20);
       System.out.println("Результат: " + result);
       
       System.out.println(multiply(4, 5));        // 20
       System.out.println(multiply(2.5, 3.5));    // 8.75
   }

Практика: создайте методы для вычисления площади круга, прямоугольника и треугольника.', 5, 'Методы', 1);

-- Внешние ключи
ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk17ucc7gjfjddsyi0gvstkqeat FOREIGN KEY (course_id) REFERENCES public.courses(id);

-- Сброс sequence
SELECT setval('public.courses_id_seq', COALESCE((SELECT MAX(id) FROM public.courses), 0) + 1, true);
SELECT setval('public.lessons_id_seq', COALESCE((SELECT MAX(id) FROM public.lessons), 0) + 1, true);