CREATE TABLE public.courses (
                                id bigint NOT NULL,
                                badge character varying(255),
                                difficulty character varying(255),
                                duration_weeks integer,
                                lessons_count integer,
                                short_description character varying(2000),
                                slug character varying(255) NOT NULL,
                                tags character varying(500),
                                title character varying(255) NOT NULL
);

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lessons (
                                id bigint NOT NULL,
                                content text,
                                "position" integer,
                                title character varying(255) NOT NULL,
                                course_id bigint NOT NULL
);

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Таблица пользователей
CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email character varying(255) NOT NULL UNIQUE,
                              username character varying(255) NOT NULL UNIQUE,
                              password_hash character varying(255) NOT NULL,
                              first_name character varying(255),
                              last_name character varying(255),
                              enabled boolean DEFAULT true,
                              created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
                              last_login timestamp without time zone
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Таблица ролей (упрощенная)
CREATE TABLE public.user_roles (
                                   user_id bigint NOT NULL,
                                   role character varying(50) NOT NULL DEFAULT 'USER'
);

-- Сначала создаем ограничения первичных ключей
ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT ukrbsoo34muf0lcryn4q2i0h3vc UNIQUE (slug);

-- Теперь добавляем данные
COPY public.courses (id, badge, difficulty, duration_weeks, lessons_count, short_description, slug, tags, title) FROM stdin;
1	Base	Лёгкая	8	20	Синтаксис, ООП, коллекции, исключения. Идеальный старт для новичков.	java-beginners	Синтаксис,Переменные,Условия,Циклы,Методы,ООП,Коллекции,Исключения	Java для начинающих
\.

COPY public.lessons (id, content, "position", title, course_id) FROM stdin;
1	Цель: поставить JDK, запустить Hello World.\n\nПример:\npublic class Main { ... }else\nя помню чудное мгновение	1	Среда разработки и первый запуск	1
2	int, double, boolean, char, String. Ввод через Scanner.	2	Переменные и типы данных	1
3	Арифметика, сравнение, логика.	3	Операторы и выражения	1
4	nextInt/nextLine и частые ошибки.	4	Ввод данных (Scanner)	1
5	Ветвления и условия.	5	if / else	1
6	Меню и выбор действий.	6	switch	1
7	Повторы до условия.	7	while	1
8	Счётчик и итерации.	8	for	1
9	int[] и базовые операции.	9	Массивы	1
10	Параметры, return, перегрузка.	10	Методы	1
11	equals, contains, split, форматирование.	11	Строки (String)	1
12	Поля, методы, конструкторы.	12	ООП: классы и объекты	1
13	private, getters/setters.	13	Инкапсуляция	1
14	extends, super.	14	Наследование	1
15	переопределение, интерфейсы (intro).	15	Полиморфизм	1
16	try/catch/finally, свои исключения.	16	Исключения	1
17	ArrayList, базовые методы.	17	Коллекции: List	1
18	HashMap, ключ-значение.	18	Коллекции: Map	1
19	чтение/запись (intro).	19	Файлы (основы)	1
20	Консольный проект на закрепление.	20	Мини-проект	1
\.

-- Добавляем внешние ключи после вставки данных
ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk17ucc7gjfjddsyi0gvstkqeat FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_unique UNIQUE (user_id, role);

-- Сбрасываем sequence на правильное значение
-- Проверяем максимальный id в таблице и устанавливаем sequence на следующее значение
SELECT setval('public.courses_id_seq', COALESCE((SELECT MAX(id) FROM public.courses), 0) + 1, true);
SELECT setval('public.lessons_id_seq', COALESCE((SELECT MAX(id) FROM public.lessons), 0) + 1, true);
SELECT setval('public.users_id_seq', 1100, true);